#!/bin/sh
output=HDMI1
res=1680x1050
laptop=eDP1

if [ ! -z $1 ]; then
  output=$1
fi

if [ "$output" = "d" ]; then
  echo "Removing output $2"
  xrandr --output $2 --off
  exit 0
fi

if [ ! -z $2 ]; then
  res=$2
fi

echo "Adding output ${output} to the right with resolution ${res}"
xrandr --output ${output} --mode ${res} --output ${laptop} --mode 1920x1080 --left-of ${output}
