#!/bin/bash
# Moves the most recently downloaded file to the current directory.
# Does not move the file if -v is supplied
latest="${HOME}/Downloads/`ls -c ~/Downloads | head -n 1`"

if [ "$1" == "-v" ]; then
  echo "$latest"
  exit
fi

move_name=./
if [ ! -z "$1" ]
  then move_name="$move_name$1"
fi

mv "$latest" "$move_name"
echo "$latest -> $move_name"
